name: Check Rust feature-powerset

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build:
    name: Building for ${{ matrix.os }}

    runs-on: ${{ matrix.os || 'ubuntu-24.04' }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - ubuntu-24.04
          - windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install rust
        uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # stable
        with:
          toolchain: stable

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2.7.7

      - name: Install cargo-hack
        run: cargo install cargo-hack --version 0.6.33 --locked

      - name: Build
        run: cargo hack check --workspace --feature-powerset --no-dev-deps
        env:
          RUSTFLAGS: "-D warnings"
